### ISSUE TITLE
MSAL.js does not work with IE11.

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-js#16]
**Repro steps**

1. Clone https://github.com/jmprieur/angular-msgraph-rest-sample-with-msaljs.git 
2. Run the application (just follow the README.md of that repo. You don't need to register the application, though.
3. execute http://localhost:8080 in Internet Explorer

**Actual** 
In IE we get a blank page, using the F12 tools, we can notice that there is a Syntax error in msal.js(3,5):
``ReferenceError: 'MSAL' is undefined``
![image](https://cloud.githubusercontent.com/assets/13203188/25239637/d1872fb4-25f0-11e7-9748-6fc91586d871.png)

**Expected**
We'd expect that is this is working in IE (it's working fine in Chrome, and Edge)

**Comment by rohitnarula7176** [comment]
We are currently compiling our typescript files to ES6 and IE 11 is having issues with that. We will have a conversation regarding this with the IE team and get back to you. If you change the property : "target": "es5", in tsconfig.json to compile to ES5, you should be able to consume MSAL.js in IE 11. Also, to be able to use popUp based login, please uncheck the Enable protected mode setting in IE by navigating to Internet Options -> Security. This is because window.open returns a NULL reference object if Enable Protected Mode is checked under Internet Options->Security->Security Level for this zone and the ZONE is different.

**Comment by rohitnarula7176** [comment]
Fixed

**Comment by vamsibassetty08** [comment]
I still see this issue with MSAL while launching the application in IE11 and console has below Error:

SCRIPT1002: Syntax error
vendor.js (148561,1)

`class AuthenticationResult {
    constructor(token, tokenType) {
        this._token = "";
        this._tokenType = "";
        this._token = token;
        if (tokenType) {
            this._tokenType = tokenType;
        }
    }
    get token() {
        return this._token;
    }
    set token(value) {
        this._token = value;
    }
    get tokenType() {
        return this._tokenType;
    }
    set tokenType(value) {
        this._tokenType = value;
    }
}`

isn't the classes supposed to be transpiled to es5? How come a Microsoft Authentication Library(MSAL) missed testing/verification in IE11 even it is reported two years before.
