### ISSUE TITLE
Library Reference Broken?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#164]
From the [home page](https://github.com/AzureAD/microsoft-authentication-library-for-js), when I click [Library Reference](https://htmlpreview.github.io/?https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/docs/classes/_useragentapplication_.msal.useragentapplication.html) I get:

>Error: Cannot load file https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/dev/docs/classes/_useragentapplication_.msal.useragentapplication.html

**Comment by rohitnarula7176** [comment]
@spottedmahn We just released version 0.1.3 of msal. The cdn links should now be fixed.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - nope, still broken for me.  Please re-open.
