### ISSUE TITLE
Code broken after upgrade from "@azure/msal-browser": "2.0.0-beta.2" to "2.0.0-beta.3"

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1895]
## Library
- [x] `@azure/msal-browser@2.0.0-beta.3`

### Issue 1
After upgrading to the latest beta it seems that the typescript type `TokenExchangeParameters` is no longer exported. What is it replaced with or what to use instead to avoid the TS error?

```typescript
export const getToken = async (request: Msal.TokenExchangeParameters) => {
  try {
    return await auth.acquireTokenSilent(request)
  } catch {
    if (isLoginPopup) {
      return await auth.acquireTokenPopup(request)
    }
    return auth.acquireTokenRedirect(request)
  }
}
```
Error:
> TS2694: Namespace '"T:/Test/node_modules/@azure/msal-browser/dist/src/index"' has no exported member 'TokenExchangeParameters'.

### Issue 2

The method `getAccount()` is no longer present. So this no longer works:

```typescript
export const setAccountId = () => {
  const account = auth.getAccount()

  if (account) {
    state.accountId = account.accountIdentifier
  } else {
    state.accountId = ""
  }
}
```
Error:
> TS2339: Property 'getAccount' does not exist on type 'PublicClientApplication'.

To fix this I tried using the [example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js) like so:

```typescript
export const loginAccount = async () => {
  if (isLoginPopup) {
    return auth.loginPopup({ redirectUri: '/', scopes: allScopes })
  }
    return auth.loginRedirect({ redirectUri: '/', scopes: allScopes })
}

export const useLogin = (router: SetupContext['root']['$router']) => {
  const login = async () => {
    loading.value = true
    try {
      const response = await loginAccount()
      if (router.currentRoute.path === '/login') { router.push('/') }
      setAccountId(response)
    } catch (error) {
      console.log('login with popup failed: ', error)
    } finally {
      loading.value = false
    }
  }

  return {
    loading: computed(() => loading.value),
    disabled: computed(() => loading.value),
    login,
  }
}

export const setAccountId = (response?) => {
  console.log('response ', response)
  if (response !== null) {
    state.accountId = response.account.homeAccountId
  } else {
    const currentAccounts = auth.getAllAccounts()
    if (currentAccounts === null) {
      state.accountId = defaultState().accountId
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
    } else if (currentAccounts.length === 1) {
      state.accountId = currentAccounts[0].homeAccountId
    }
  }
}
```
Error:
> TypeError: Cannot read property 'account' of undefined

#### Fix for issue 2 is:
Maybe the example code should be updated from:
```js
function handleResponse(resp) {
    if (resp !== null) {
````
to:
```js
function handleResponse(resp) {
    if (resp && resp.account) {
   // or:
   if (response != null) {
```

What is the correct TS type for the `response` object here?

Thank you for your help.

**Comment by pkanher617** [comment]
@DarkLite1 
### Issue 1:
We replaced `TokenExchangeParameters` with `SilentFlowRequest`. I've updated the docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#silentflowrequest), but it may not be clear enough so I will be sure to add a breaking changes section somewhere to call these changes out.

### Issue 2:
Correct, getAccount() is deprecated. `@azure/msal-browser` now supports multiple accounts, and so the flow looks a bit more like this now: 
```javascript
function handleResponse(resp) {
    if (resp !== null) {
        username = resp.account.username;
        ...
    } else {
        // need to call getAccount here?
        const currentAccounts = myMSALObj.getAllAccounts();
        if (currentAccounts === null) {
            return;
        } else if (currentAccounts.length > 1) {
            // Add choose account code here
        } else if (currentAccounts.length === 1) {
            // Single Account usecase
            username = currentAccounts[0].username;
            ...
        }
    }
}
```

There is more information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md) about accounts.

**Comment by DarkLite1** [comment]
Thank you for the help, much apprecaited as I'm a beginner in all this. 

### Issue 1

When swapping out `TokenExchangeParameters ` for `SilentFlowRequest` we still have a problem with the type for `request`: Is there a more generic type? I tried combining both types like `request: Msal.AuthorizationUrlRequest | Msal.SilentFlowRequest`, but that's not accepted either.

```typescript
export const getToken = async (request: Msal.SilentFlowRequest) => {
  try {
    return await auth.acquireTokenSilent(request)
  } catch {
    if (isLoginPopup) {
      return await auth.acquireTokenPopup(request)
    }
    return auth.acquireTokenRedirect(request)
  }
}
```
Error:
> TS2345: Argument of type 'SilentFlowRequest' is not assignable to parameter of type 'AuthorizationUrlRequest'

### Issue 2

What is the correct typescript type for `response` or in your example `resp`?

```typescript
function handleResponse(resp) {
    if (resp !== null) {
        username = resp.account.username;
        ...
    } else {
        // need to call getAccount here?
        const currentAccounts = myMSALObj.getAllAccounts();
        if (currentAccounts === null) {
            return;
        } else if (currentAccounts.length > 1) {
            // Add choose account code here
        } else if (currentAccounts.length === 1) {
            // Single Account usecase
            username = currentAccounts[0].username;
            ...
        }
    }
}
```

**Comment by DarkLite1** [comment]
@tnorling sorry for involving you here but could have a second look at this? Maybe my request is incorrect or I'm doing it wrong.

**Comment by DarkLite1** [comment]
Closing this one as I converted my function like this:

```typescript
export const getToken = async (scopes: string[]) => {
  const request = {
    scopes: scopes,
    account: account.value,
  }
  try {
    return await auth.acquireTokenSilent(request)
  } catch {
    if (isLoginPopup) {
      const res = await auth.acquireTokenPopup(request)
      setAccount(res.account)
      return res
    }
    return auth.acquireTokenRedirect(request)
  }
}
```

Still learning as I go, thanks for the help everyone.

**Comment by pkanher617** [comment]
@DarkLite1 Sorry for missing the questions. I've added a typescript sample, let me know if it helps.

**Comment by DarkLite1** [comment]
@pkanher617 thank you for getting back to me but I think you posted the wrong link to the typescript sample?
