### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 0 when calling PublicClientApplication.prototype.logout()

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2161]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
When calling PublicClientApplication.prototype.logout(), sometimes it throws an exception
"Uncaught (in promise) SyntaxError: Unexpected token e in JSON at position 0"
The stack trace is minified on our end but it says 
at JSON.parse
at t.getItem
at index.6b5ff599.js:2
at Array.forEach
at t.e.removeAccountContext
at t.e.removeAccount
at index.6b5ff588.js:2
at Array.forEach
at t.e.removeAllAccounts
at t.clear

Then after reloading the page, we get errors (probably due to inconsistent state after some failure in logging out):
"No_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken()"

## Error Message
"Uncaught (in promise) SyntaxError: Unexpected token e in JSON at position 0"

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        loadFrameTimeout: 30000,
        tokenRenewalOffsetSeconds: 60,
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

Logout should work and not thrown an error

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [X] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
@thoo1 could you please provide a code snippet of where you are using `logout` in your code?

Are there any values in your localStorage (that were not created by MSAL) that contain one of [these strings](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/92e7f3d7db0aa6ac81d3847b0b0b7a236bc90557/lib/msal-common/src/utils/Constants.ts#L220-L224) in their key? For example, are you manually storing your access tokens in local storage?

**Comment by thoo1** [comment]
@technical-boy we just call `this.publicClientApp.logout();`
We did have our own implementation of the implicit grant flow that we are trying to migrate off of, however I checked the keys we store and they do not contain "IdToken", "AccessToken", "RefreshToken"

**Comment by rSandona** [comment]
I also ran into this issue updating from V1 to V2

**Comment by maxmalik** [comment]
we've got the same issue.
we are migrating from adal to msal and have multiple apps running on the same domain.
some apps are still using adal and the issue is reproduced when you switch between apps and then try to logout 
The reason of the issue is that format of id token value in local storage is different in adal (plain string) vs msal (json).

**Comment by jmckennon** [comment]
The linked PR (#2115) should fix this issue, it's in the review process at the moment.

**Comment by DaniusLabs** [comment]
so what's the solution for this, still happening in 2.4 in Safari.  Thanks. 

Daniel.

**Comment by tnorling** [comment]
@DaniusLabs We believe the linked PR should fix this issue. It is slated for release in 2.5

**Comment by DaniusLabs** [comment]
Thanks @tnorling 
My questions was more about what should I offer as means to logout to my current safari users?
When is 2.5 scheduled for?

Thank you.

**Comment by tnorling** [comment]
@DaniusLabs I was actually corrected, this fix was just released today in version 2.4.1. Please give that a go and open a new issue if you continue to see this error. Thanks!

**Comment by DaniusLabs** [comment]
Thanks @tnorling 
This seems to work now. Thank you very much!
