### ISSUE TITLE
acquireTokenPopup does not call back when window is closed

### ISSUE THREAD

**Issue by jnxxx** [AzureAD/microsoft-authentication-library-for-js#269]
... as a result the client code waits infinitely for a token (unless I implement some check myself).

It seems however, the function openWindow should have functionality to handle this. In fact it is polling  every 1 ms.
But in this line: if (popupWindow && popupWindow.closed && instance._loginInProgress)
_loginInProgress is false (at least when called by acquireTokenPopup).

I have now changed it to: if (popupWindow && popupWindow.closed && (instance._loginInProgress || instance._acquireTokenInProgress))
This seem to work.

I am using msal.js version: 0.1.5

**Comment by navyasric** [comment]
@jnxxx Can you please download the latest version of MSAL and let us know if the issue persists. 
Also please provide information on the browser(including version) and the type of user accounts you are trying to authenticate.

**Comment by nehaagrawal** [comment]
closing this issue since this issue is pretty old and it may have been resolved in the latest version and due to lack of activity from the user.

**Comment by plakak** [comment]
I can confirm that the issue is still present. 
Chromium: Version 70.0.3538.77 (Official Build) Arch Linux (64-bit)
