### ISSUE TITLE
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by Michael-006** [AzureAD/microsoft-authentication-library-for-js#6492]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

?

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.4

### Public or Confidential Client?

Public

### Description

When having special characters in the displayName like _my tester special charactersčćęèéêëėįìíîï_ msal throws an error "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded." 

After this error I'm getting:

ClientAuthError: token_parsing_error: Token cannot be parsed. Please review stack trace to determine root cause. Failed with error: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### Error Message

DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### MSAL Configuration

```javascript
not relevant
```

### Relevant Code Snippets

```javascript
try {
    const oe = S(Q);
    return JSON.parse(oe)
} catch (oe) {
    throw d.e.createTokenParsingError(oe)
}
```

### Reproduction Steps

Set display name to my tester special charactersčćęèéêëėįìíîï

### Expected Behavior

no error, should decode correctly

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by Mexx77** [comment]
we see the same issue with the special character ł in the lastname of the user

**Comment by jansepke** [comment]
possible duplicate of #6476

**Comment by fredliex** [comment]
atob can't process non-latin, ex japanese or chinese characters.
maybe change base64 encode/decode like follow
encode : btoa(unescape(encodeURIComponent(str)))
decode: decodeURIComponent(escape(atob(decodedStr)))

**Comment by fredliex** [comment]
in commit https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/2ef47fe40e817cfd4428ed75dd8dbf11a3f13632  , some code are missing.



https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b69ed83ede29bd39b04eb71ae7c15f0a983e0442/lib/msal-browser/src/encode/Base64Decode.ts#L24

should be as follows
```csharp
const binString = atob(base64String.replace(/-/g, "+").replace(/_/g, "/"));
```

**Comment by loebi-ch** [comment]
I just tested the new version 3.0.5 and the included #6535 bug fix solves the problem. Thank you!

**Comment by tnorling** [comment]
This has been fixed in 3.2.0

**Comment by MohanMugi** [comment]
@fredliex you are a life saver...
Thank you!

**Comment by MaikL** [comment]
Are there different rollout phases for this bugfix?
In the AzureEU Cloud I still get the same error, when I try to add a password to my gateway.
> Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by tnorling** [comment]
> Are there different rollout phases for this bugfix? In the AzureEU Cloud I still get the same error, when I try to add a password to my gateway.
> 
> > Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

This is a client library, not a service, there is no "rollout". Your application or whatever is invoking MSAL.js will need to install and deploy the latest version with the fix.

**Comment by MaikL** [comment]
OK, sorry I missed to reference some circumstances.
The Error occurs on the Gateway configuration page of Power BI (https://app.powerbi.com/groups/me/gateways).
When I try to enter the username and password for a Basic Authentification Method. So I think this is on Microsofts side to add these changes.

**Comment by MohanMugi** [comment]
Hi,

Try this solution, it should work.
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6492

const binString = atob(base64String.replace(/-/g, "+").replace(/_/g, "/"));

Best Regarding,
Mohan Palanisamy

**Comment by MaikL** [comment]
I am sorry, my problem is solved. The error was, that I installed the "standard Gateway" not the "personal Gateway".
Why there is no specific error, which hints to this problem is beyond my horizon.
