### ISSUE TITLE
Inconsistent behaviour for different user account types

### ISSUE THREAD

**Issue by mlankamp** [AzureAD/microsoft-authentication-library-for-js#669]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
<pre><code>
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX
</code></pre>

## Library version

<pre><code>
Library version: 1.0.0-preview.4
</pre></code>
## Current behavior
I'm using the latest preview version against a Azure Domain (example.onmicrosoft.com) that has the following users in the domain:
- user@example.onmicrosoft.com
- live-id's (user@hotmail.com)
- external Azure AD users (user@external.onmicrosoft.com)

The external users are invited using the graph api. Some users have different username/email combinations, so I enabled the sid claim (see #623).

When I call acquireTokenSilent for the different kind of accounts is different. 

## Expected behavior
<pre><code>
const config: Configuration = { auth: {....}, cache: {.....}};
const authcontext = new UserAgentApplication(config);
const request: AuthenticationParameters = {
   scopes: ['user_read'],
   account: this.authcontext.getAccount(),
};
this.authcontext.acquireTokenSilent(request).then((value) => { .... });
</code></pre>

I pass the account so the sid is used in the acquire token call, this causes the following error (fo live-id's):
AADSTS90005: Unable to complete request. The request was invalid since sid and login_hint cannot be used together.

If I add prompt: 'none' to the AuthenticationParameters, the following error is shown:
AADSTS900051: Unable to complete request. The request was invalid since sid and domain_hint cannot be used together.

If I don't use the account parameter, this works for live-id's and other accounts, but not for the invited accounts where email and username are different.

## Minimal reproduction of the problem with instructions
- Add different kind of users in the AD
- Try to call acquireTokenSilent for each account

**Comment by aashiman** [comment]
@mlankamp  if you pass sid, please do not pass login_hint or domain_hint as the protocol does not work when these do not align i.e. login hint has a diff user than the one in the sid. 

Please refer to this and let us know if this can be called out in an easier way
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Sso

**Comment by sameerag** [comment]
Also with the new APIs this is **sid** or **login_hint** or **account** - Only one of these can be passed in the request.

**Comment by mlankamp** [comment]
I'm using the new API's (1.0.0-preview.4) and I'm only providing the **account**:

<pre><code>
const request: AuthenticationParameters = {
    scopes: ["user_read"],
    account: this.authcontext.getAccount(),
};

this.authcontext.acquireTokenSilent(request).then((value) => {
    resolve(value.accessToken);
});
</code></pre>

My point is that when you login with an live-id (that is added as a guest in an Azure AD tenant) the API adds the login_hint and the sid. This causes the error thrown.
By reading the source code, I can see where the login_hint is added. So to prevent that, I added the prompt=none. This causes a different behaviour.

This only happens when you add the following in the manifest of the Azure AD application:
<pre><code>"optionalClaims": {
  "idToken": [
    {
      "name": "sid",
      "source": null,
      "essential": true,
      "additionalProperties": []
    }
  ],
  "accessToken": [],
  "saml2Token": []
},</code></pre>

**Comment by sameerag** [comment]
Sure. Let me take a look at this and see if we are adding hints when we don’t need to. The idea is to fall back on the info the api has if the user did not populate any hint data.

**Comment by mlankamp** [comment]
I've created an example https://msaljs.azurewebsites.net/ (based on the VanillaJSTestApp/index.html). In the function `acquireTokenPopupAndCallMSGraph` i've added the line `request.account = myMSALObj.getAccount();` If I remove this line, the application works as expected.

The sign-in works, but the request token has a failure. The url called is:

https ://login.microsoftonline.com/65382380-7f03-4be4-945d-ebc0c32d0372/oauth2/v2.0/authorize?response_type=token&scope=User.Read%20openid%20profile&client_id=90bcec70-2963-4556-8c34-1f107feb0fd1&redirect_uri=https%3A%2F%2Fmsaljs.azurewebsites.net%2F&state=b465b7a9-e7f3-4328-98ee-3b9b2ac4e19f&nonce=62310c2a-33a5-40b1-9986-11113b78b1bc&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.0.0-preview.4&**sid=f4be052d-5ac5-4627-91a2-ed9c0fc7a59c**&login_req=00000000-0000-0000-eea9-2aa55a5046ee&domain_req=9188040d-6c67-4c5b-b112-36a304b66dad&domain_hint=consumers&**login_hint=********%40lankamp.net**&client-request-id=d6e47b21-4dcb-4432-a74d-7ee3e1ce1ed6&prompt=none

I've highlighted the duplicate hints. If you want to test yourself, I can add your live-id to this tenant.

**Comment by sameerag** [comment]
Yes please. Can you please add the live id: "testmsal@outlook.com"? I will reach out later in the day once the sort this out.

**Comment by mlankamp** [comment]
I've added the live-id to my tenant (you should receive an invite email)

**Comment by sameerag** [comment]
Thanks much. Received the email.

**Comment by mlankamp** [comment]
Any update? Maybe reopen this issue?

**Comment by sameerag** [comment]
Sorry @mlankamp ... heads down in a release. But this is something we want to fix before that. I am hoping I will have something today.

**Comment by mlankamp** [comment]
Tested with version 1.0.0, the error still exists

**Comment by sameerag** [comment]
@mlankamp Yes, no fix has gone in yet. I am yet to debug this. If a fix is identified, we want it to go in the next release. I will update once I have a test branch for you to try out.

We are still swamped with some of the release related work and please expect some delaY.

**Comment by sameerag** [comment]
@mlankamp can you please try the fix in #700 and let us know if it fixes your issue? Looks like there is one case where "sid" check is missing when adding "login_hint" and that could be causing this behavior.

**Comment by mlankamp** [comment]
@sameerag I've pulled the version from your pull request and build this version, but the problem still exists. But I get an different error:

AADSTS900051: Unable to complete request. The request was invalid since **sid** and **domain_hint** cannot be used together.

**Comment by sameerag** [comment]
@mlankamp Thanks for the followup. This is interesting because service always told us that 'login_hint' and 'sid' cannot be sent together but looks like they have further restrictions when 'sid' is enabled. I am following up with them to clarify the requirement. 

The code changes are indeed simple. I will get back once I hear back from them to make this change.

**Comment by mlankamp** [comment]
Looks like SID in combination with live-ids is restricted, normal AD accounts don't have this problem.

**Comment by sameerag** [comment]
@mlankamp  The latest I have on this: we are internally clarifying the requirements with the service to standardize the behavior when the user sets "sid". I will try to close this asap to have this make it to the next patch release.

**Comment by mlankamp** [comment]
If I have to test a PR, just let me know.

**Comment by sameerag** [comment]
#700 is modified with the needed check. We are still finalizing the changes but the needed functionality is in, you can test it and let us know if it works for all cases you need.

**Comment by sameerag** [comment]
@mlankamp #700 is now part of the latest patch release msal 1.01. Can you please confirm if this issue is fixed?

**Comment by sameerag** [comment]
@mlankamp Closing this as PR #700 is now released. Please let me know if there are any more edge cases you see that are not addressed with this PR.

**Comment by mlankamp** [comment]
@sameerag I did a new test today with library version 1.0.1 and the problem still exists. When I add a live-id to my Azure AD tenant and try to login with the live-id and the SID parameter is enabled in the application I still receive the following error:

AADSTS900051: Unable to complete request. The request was invalid since sid and domain_hint cannot be used together.

**Comment by sameerag** [comment]
@mlankamp That is interesting. I know you have added me before to your app with id: testmsal@outlook.com; Is that still added? 

I want to test this once to see what is missing. Apologies for the back and forth, we are working on adding a comprehensive test sample for all hints to have better gating in future.

**Comment by mlankamp** [comment]
Yes, this user is still added

**Comment by tnorling** [comment]
@mlankamp So sorry this went unanswered for so long. Is this still an issue in `msal@1.3.0`? We made some changes to the domain_hint parameter in the newest release that may fix this issue.

**Comment by tnorling** [comment]
Closing as we believe this has been fixed. Let us know if we need to reopen it.
