### ISSUE TITLE
Getting Type 'InteractionStatus' is not assignable to type '"startup"' using node-browser and typescript

### ISSUE THREAD

**Issue by Employee87** [AzureAD/microsoft-authentication-library-for-js#6706]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I was using node-browser 2.5 with javascript/typescript, based on this vue sample project.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app

Then I upgraded to msal v3 and followed their upgrade guide which was simple, and it only had me add in `await msalInstance.initialize();` right after making a new instance of `PublicClientApplication`. However, on this file now

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app/src/plugins/msalPlugin.ts

I am getting a typescript error.

[image](https://i.stack.imgur.com/gnHFZ.png)

Which leads me to think there was another breaking change. How can I fix this?

Thanks

### Error Message

Type 'InteractionStatus' is not assignable to type '"startup"'.
  Type '"login"' is not assignable to type '"startup"'.ts(2322)

### MSAL Configuration

```javascript
{
auth: {}
}
```

### Relevant Code Snippets

```javascript
{
auth: {}
}
```

### Reproduction Steps

typescript error, you see it right away

### Expected Behavior

no typescript error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, None (Server), Other

### Source

External (Customer)

**Comment by jason8399** [comment]
You can change https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/70ab381446cf45f42b70f2ad3c59560783e6a627/samples/msal-browser-samples/vue3-sample-app/src/plugins/msalPlugin.ts#L37-L41

to: 
``` typescript
const state = reactive<{
    instance: PublicClientApplication
    inProgress: InteractionStatus
    accounts: AccountInfo[]
  }>({
    instance: msalInstance,
    inProgress: inProgress,
    accounts: accounts
  })
```
then it would work.

**Comment by Employee87** [comment]
that works

**Comment by tnorling** [comment]
Closing as it sounds like this was resolved.

**Comment by jaoord** [comment]
this is still a problem

**Comment by giuliohome** [comment]
Yes, this is still a problem!

But thanks @jason8399 : adding  

```
<{
    instance: PublicClientApplication
    inProgress: InteractionStatus
    accounts: AccountInfo[]
  }>
```
makes it work 🎉 

Why isn't this change merged?

**Comment by ecdeaver** [comment]
Hello, 
 I am also having this issue. Trying to use this library for work and this is a unexpected error. 
 
 @tnorling  can this change that @jason8399  presented be merged into the codebase?
